stages:
  - test
  - deploy

test_pytest:
  stage: test
  image: python:3.10
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip install --upgrade pip
    - pip install .
    - pip install .[test]
    - pytest test/

deploy_pypi:
  stage: deploy
  image: python:3.10
  only:
    - tags
  except:
    - branches
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip install --upgrade pip
    - pip install .[deploy]
    - python -m build
    - export TWINE_USERNAME=__token__
    - export TWINE_PASSWORD=$TWINE_PASSWORD
    - twine upload dist/*