name: pytest

on:
  push:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          runs-on: ubuntu-latest
          env:
            NODE_VERSION: 16.x

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        runs-on: ubuntu-latest
        env:
          NODE_VERSION: 16.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]

      - name: Run tests with pytest
        run: |
          pytest test/